### ISSUE TITLE
Air Purifier 4 Pro ESP32 Firmware Dump

### ISSUE THREAD

**Issue by epiller** [dhewg/esphome-miot#41]
Hey @dhewg, thanks for this amazing repo, it's been really great and works flawlessly. 
Even though this isn't an issue with your repo, I'm opening it as a public cry for help because I forgot to make an ESP32 firmware dump and now I can't go back to the original firmware in order to update the main controller's firmware.
  
### If anyone reading this has a Xiaomi Air Purifier 4 Pro and wants to help: Can you please make a dump of your ESP32 firmware before flashing ESPHome and post it here?

Once connected to the chip, you can make the firmware dump using the following command: `esptool.py -b 115200 read_flash 0 ALL xiaomi-air-purifier-4-pro-firmware-dump.bin`

**Comment by duckimann** [comment]
sorry i dont have a firmware dump

**Comment by duckimann** [comment]
just curious, why do you have to update the main controller firmware?

**Comment by duckimann** [comment]
just curious, why do you have to update the main controller firmware? @epiller

**Comment by jhbruhn** [comment]
[xiaomi-air-purifier-4-pro-firmware-dump-clean.zip](https://github.com/user-attachments/files/18726157/xiaomi-air-purifier-4-pro-firmware-dump-clean.zip)

I forgot to factory-reset my purifier before doing this dump, so I removed my wifi credentials manually with a hex-editor. Hopefully I didn't break anything, but I guess this is worth a shot!

**Comment by dhewg** [comment]
Nice, that should settle it!

@epiller It's not clear why you want/need to update the MCU firmware. If there's a problem with one version, which is fixed by a newer one: That would be a relevant information for other users here as well: so please share any insights if that's the case!

**Comment by epiller** [comment]
@jhbruhn Thank you so much!
@dhewg The Level and motor RPM are updated too infrequently, which I'm hoping is something that will be fixed in a newer firmware. Thanks to @jhbruhn, I can revert back to the stock firmware, update the main MCU, and go back to your firmware.

**Comment by cristianchelu** [comment]
> [@jhbruhn](https://github.com/jhbruhn) Thank you so much! [@dhewg](https://github.com/dhewg) The Level and motor RPM are updated too infrequently, which I'm hoping is something that will be fixed in a newer firmware. Thanks to [@jhbruhn](https://github.com/jhbruhn), I can revert back to the stock firmware, update the main MCU, and go back to your firmware.

For what it's worth, I had success with manually queuing the update command, try to see if this works, replacing `get_properties 9 1` with your actual motor speed SIID and PIID numbers:
```yaml
time:
  - platform: homeassistant
    on_time:
      - seconds: /1 # every 1 second, for example
        then:
          - lambda: id(miot_main).queue_command("get_properties 9 1");
```

More info: https://esphome.io/components/time/index.html#on-time-trigger

I use mine to approximate the active power on-device instead of using Powercalc integration (a few power metering smart socket measurements at different speeds + online exponential fit calculator for the numbers):
```yaml
- platform: "template"
    name: "Active power"
    id: active_power
    state_class: measurement
    unit_of_measurement: W
    icon: mdi:flash
    accuracy_decimals: 2
    lambda: |-
      float speed = id(motor_speed).state;
      float anion = id(ionizer).state ? 1.0 : 0.0;
      float fan = 1.17067 * std::pow(2.71828, 0.00157301 * speed);
      return fan + anion;
    update_interval: 1s
    on_value: 
      then:
        lambda: 'id(miot_main).queue_command("get_properties 9 1");'
```
