### ISSUE TITLE
Scheduler doesn't dispense at good time

### ISSUE THREAD

**Issue by Idaho947** [dhewg/esphome-miot#48]
Hello,

I have a scheduling problem. I've scheduled two feedings: one at 6.35 am, the other at 7 pm.

This morning, they were served at 6:15 a.m. and it was the 7 p.m. ration that was indicated as served on the HA card.

I'm noticing that my time zone indications aren't right, but I don't know how to change them. I'm in UTC+1 (Paris) in winter time.
This wouldn't explain the time difference, however, since if it's a question of time zone, it should have read xx:30.

![Image](https://github.com/user-attachments/assets/70807ed3-19eb-47ed-a99f-1265b66aec67)

Perhaps important information: I never connected the device to the Xiaomi server, I inserted the firmware straight out of the box.

Here are some esphome log for the device :

[logs_espgamelle_logs.txt](https://github.com/user-attachments/files/18795060/logs_espgamelle_logs.txt)

**Comment by cristianchelu** [comment]
There are two "issues":

1. You need to change the timezone in the configuration YAML, as explained in the comments:

```yaml
substitutions:
  # Timezone for automatic daylight savings time (DST) adjustment
  # See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for options
  # Change as needed for your location
  # e.g. "Europe/London", "America/New_York", "Asia/Tokyo"
  auto_dst_timezone: "Etc/GMT" # <-- In your case this should say "Europe/Paris"
```
This will handle the daylight savings time adjustment for you twice a year :)

2. The feeder's main microcontroller has some bugs in synchronizing the time, it doesn't work all the time, explaining the +15 minutes difference in dispensing the 7am (GMT+0) portion.

We haven't figured out what exactly happens or how to immediately fix it, but in all reports the issue fixes itself after 24/48h of the feeder being powered on.

See [this comment](https://github.com/dhewg/esphome-miot/issues/39#issuecomment-2495514080).

In short,
Change your `auto_dst_timezone` to fit your location and wait 24~48h, your issues should be gone.

Cheers!

**Comment by cristianchelu** [comment]
> Can I change the time zone and send the update via OTA in esphome in home assistant

Yes, as normal for any ESPHome device.

If you did not delete the OTA section in the config and you have your OTA password saved in the secrets file:
```yaml
ota:
  - platform: esphome
    password: !secret feeder_ota_password
```
